name: Scheduled Health Check
on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *" # recommended: */30 * * * *   - run every 30mins
    #- cron: "0 0 * * *" # recommended: */30 * * * *   - run every 30mins
jobs:
  health_check_job:
    runs-on: ubuntu-latest
    name: Check all sites
    steps:
      - uses: actions/checkout@v2
      - name: Run Health Check
        id: health_check
        run: bash ./script/health-check.sh

      - name: Run Notification
        env:
          HEALTH_STATUS: ${{ join(steps.health_check.outputs.*, '\n') }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: notifcation
        run: bash ./script/notification.sh
